/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.transfers;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        TransferApplication classUnderTest = new TransferApplication();
//        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
