/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.transfers;

import com.google.inject.Injector;
import com.transfers.api.CustomerController;
import com.transfers.api.PaymentController;
import com.transfers.service.CustomerService;
import com.transfers.service.PaymentService;
import org.mybatis.guice.XMLMyBatisModule;
import org.mybatis.guice.datasource.helper.JdbcHelper;
import spark.Service;

import static com.google.inject.Guice.createInjector;

public class TransferApplication {
    private static final int PORT = 8080;
    private static Injector injector = createInjector(new XMLMyBatisModule() {
        @Override
        protected void initialize() {
            install(JdbcHelper.HSQLDB_Embedded);
            bind(CustomerService.class);
            bind(PaymentService.class);
        }
    });

    public static void main(String[] args) {
        Service spark = Service.ignite().port(PORT);
        injector.getInstance(CustomerController.class).configure(spark);
        injector.getInstance(PaymentController.class).configure(spark);
    }
}
